apiVersion: v1
kind: Service
metadata:
  name: test1-label-ann-svc
  labels:
    app: admission-webhook-example
    app.kubernetes.io/name: sleep
    app.kubernetes.io/instance: sleep
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/component: dummy
    app.kubernetes.io/part-of: admission-webhook-example
    app.kubernetes.io/managed-by: kubernetes
  annotations:
       service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None" 
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: admission-webhook-example
